### ISSUE TITLE
How do I install this?

### ISSUE THREAD

**Issue by sondresorbye** [literalpie/ngx-flare#1]

**Comment by NidasioAlberto** [comment]
I'm trying too...

**Comment by literalpie** [comment]
Thank you for your interest. I haven't published to npm or anything because this is mostly just a POC. To use this you could do the following: 
1. clone the repo
2. `npm install`
3. `ng build ngx-flare`
4. `npm pack ./dist/ngx-flare`
5.  add `"ngx-flare": "ngx-flare-0.0.1.tgz"` to your `package.json` dependancies
6. `npm install`
7. `import { NgxFlareModule } from 'ngx-flare';` (and add to your module imports - use like any angular module)

**Comment by literalpie** [comment]
You can skip the first 4 steps if you download [this tarball/tgz](https://firebasestorage.googleapis.com/v0/b/ngx-flare.appspot.com/o/ngx-flare-0.0.1.tgz?alt=media&token=bb1c8c4f-78fd-4272-8173-f60158ae4f0f)

**Comment by NidasioAlberto** [comment]
Thanks, I’ll try it as soon as possible

**Comment by NidasioAlberto** [comment]
I've copied the tarball/tgz file in my project, included the library in the package.json and also added gl-matrix library but it keeps asking for a flare dependency:
```
ERROR in The target entry-point "ngx-flare" has missing dependencies:
 - flare
```

**Comment by literalpie** [comment]
Oh yes, sorry. I forgot about that part!

You will need to get the flare.js file. You can download it from the deps folder in this project.

Then you will need to add this to your tsconfig.json in the `compilerOptions`:
```
"paths": {
      "flare": [
        "deps/flare" // < --- make this match whatever the location of your flare.js file is
      ]
}
```

Really, what I would recommend is just cloning this repo and playing around with it inside the project. (`nom install` and `ng serve`).
